#!/bin/sh

set -e

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    update-alternatives --install /usr/bin/firefox \
        x-www-browser /usr/bin/firefox 40
    update-alternatives --install /usr/bin/firefox \
        gnome-www-browser /usr/bin/firefox 40
fi

